/*
    SimWindows - 1D Semiconductor Device Simulator
    Copyright (C) 2013 David W. Winston

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//#define CUSTOM

#define STRICT

typedef double			prec;
typedef int  			error;
typedef int				logical;
typedef unsigned long	flag;
typedef short 			AlloyType;
typedef short 			MaterialType;
typedef short 			MaterialParam;

typedef short		DopingType;
#define ACCEPTOR	0
#define DONOR		1

typedef short		RegionType;
typedef RegionType	NodeType;
#define BOUNDARY	0
#define BULK		1
#define QW			2

typedef short		MirrorType;
#define METAL_MIRROR	1
#define DBR_MIRROR		2

typedef short		CavityType;
#define EDGE_CAVITY		1
#define SURFACE_CAVITY 	2

typedef short		SolveType;
#define NO_SOLUTION		0
#define CHARGE_NEUTRAL	1
#define EQUILIBRIUM		2
#define STEADY_STATE	3
#define TRANSIENT		4

typedef short		StatusType;
#define NO_DEVICE		0
#define SIMULATE		1
#define CONVERGED		2
#define NOT_CONVERGED	3

typedef long						FunctionType;
#define	NON_FUNCTION					0
#define CONSTANT						1
#define POLYNOMIAL						2
#define USER_FUNCTION 					3
#define BAND_GAP_MODEL					4
#define THERM_CONDUCT_MODEL				5
#define POWER_ABSORPTION_MODEL			6
#define POWER_ABSORPTION_BAND_GAP_MODEL 7
#define EXP_ABSORPTION_MODEL			8
#define EXP_ABSORPTION_BAND_GAP_MODEL	9
#define ALGAAS_REFRACTIVE_INDEX_MODEL	10
#define ALGAAS_ABSORPTION_MODEL			11
#define MOBILITY_MODEL					12

enum ScaleType { UNNORMALIZED=1, NORMALIZED };
enum AxisType { LIN=0, LOG };
enum OperationType { EXACT, NEGATIVE, ABS };
enum NumberFormat { NORMAL=1, SCIENTIFIC };
enum FileType { INPUT_FILE=1, STATE_FILE };
enum MacroType { VOLTAGE_MACRO=1 };
enum ElementSide { FIRSTHALF, SECONDHALF };
enum NodeSide { PREVIOUS_NODE=1, CURRENT_NODE, NEXT_NODE };
enum ValidatorType { INCLUSIVE, EXCLUSIVE };

#ifndef NULL
	#define NULL	0
#endif

#ifndef FALSE
	#define FALSE	0
#endif

#ifndef TRUE
	#define TRUE	!FALSE
#endif

#ifndef MAXPATH
	#define MAXPATH 80
#endif

#ifndef MAXDIR
	#define MAXDIR  66
#endif

#ifndef MAXFILE
	#define MAXFILE 9
#endif

#ifndef MAXEXT
	#define MAXEXT  5
#endif

#define MAX_NUMBER_PLOTS	6
#define MAX_LABEL_LENGTH	30
#define MAX_TITLE_LENGTH	50
#define MAX_MATERIAL_NAME	30
#define MAX_ALLOY_NAME		30

// MARGIN parameters
#define LEFT_MARGIN   70
#define RIGHT_MARGIN  35
#define TOP_MARGIN    45
#define BOT_MARGIN    60

// PLOT flags
#define PLOT_MODE_DATA			0x01
#define PLOT_MODE_TITLES		0x02
#define PLOT_MODE_TICS			0x04
#define PLOT_MODE_BORDER		0x08
#define PLOT_MODE_ENTER_GRAPH	0x10
#define PLOT_MODE_EXIT_GRAPH	0x20

#define PLOT_MODE_COMPLETE		0x0F

// SIM parameters.
#define SIM_pi   		3.14159265358979323846
#define SIM_trilog_1    1.20205690
#define SIM_sqrtpi  	1.77245385091
#define SIM_q    		1.6021892E-19					// C
#define SIM_mo   		9.109534E-31					// kg
#define SIM_h    		6.626176E-34					// J s
#define SIM_hb   		1.0545887E-34					// J s
#define SIM_k    		1.38E-23						// J/K
#define SIM_k_eV 		8.62E-5                         // eV/K
#define SIM_eo			8.854e-14						// F/cm
#define SIM_c			3e10							// cm/s

// NORM parameters.
#define NORM_charge 1.6021892E-19					// C
#define NORM_temp 300.0								// K
#define NORM_mobility 1.0							// cm2/V s

// MAT Parameters
#define MAT_NO_ALLOY						0
#define MAT_NO_MATERIAL						0

#define MAT_BAND_GAP						1
#define MAT_ELECTRON_AFFINITY				2
#define MAT_PERMITIVITY						3
#define MAT_REFRACTIVE_INDEX				4
#define MAT_ABSORPTION						5
#define MAT_THERMAL_CONDUCTIVITY			6
#define MAT_DERIV_THERMAL_CONDUCT			7
#define MAT_ELECTRON_MOBILITY				8
#define MAT_HOLE_MOBILITY					9
#define MAT_ELECTRON_DOS_MASS				10
#define MAT_HOLE_DOS_MASS					11
#define MAT_ELECTRON_COND_MASS				12
#define MAT_HOLE_COND_MASS					13
#define MAT_ELECTRON_SHR_LIFETIME			14
#define MAT_HOLE_SHR_LIFETIME				15
#define MAT_ELECTRON_ENERGY_LIFETIME 		16
#define MAT_HOLE_ENERGY_LIFETIME 			17
#define MAT_ELECTRON_AUGER_COEFFICIENT  	18
#define MAT_QW_ELECTRON_AUGER_COEFFICIENT 	19
#define MAT_HOLE_AUGER_COEFFICIENT			20
#define MAT_QW_HOLE_AUGER_COEFFICIENT       21
#define MAT_B_B_RECOMB_CONSTANT				22
#define MAT_QW_B_B_RECOMB_CONSTANT			23
#define MAT_ELECTRON_COLLISION_FACTOR		24
#define MAT_HOLE_COLLISION_FACTOR			25

#define MAT_MAX_NUMBER_PARAMETERS		25

#define MAT_MAX_NUMBER_PARAMETER_VAR	6

// DERIVATIVE flags.
#define D_PSI	  	0x0001
#define D_ETA_C   	0x0002
#define D_ETA_V   	0x0004
#define D_TEMP	  	0x0008
#define ALL_DERIV 	0x000F

// ERROR parameters
#define ERROR_NONE							0

#define ERROR_MEM_DEVICE_GRID				-1
#define ERROR_MEM_QW						-2
#define ERROR_MEM_CONTACT					-3
#define ERROR_MEM_CAVITY					-4
#define ERROR_MEM_SOLUTION_GRID				-5
#define ERROR_MEM_SOLUTION_ELEMENT			-6
#define ERROR_MEM_PLOT						-7
#define ERROR_MEM_SPECTRAL_COMP				-8
#define ERROR_MEM_PARSE_DEVICE				-9
#define ERROR_MEM_PARSE_TERMS				-10
#define ERROR_MEM_DEVICE_INPUT				-11
#define ERROR_MEM_STRING_LIST				-12
#define ERROR_MEM_SURFACE					-13
#define ERROR_MEM_SOLUTION_ARRAYS			-14
#define ERROR_MEM_USER_FUNCTION				-15
#define ERROR_MEM_ALLOY						-16
#define ERROR_MEM_MATERIAL					-17
#define ERROR_MEM_MATERIAL_MODEL			-18

#define ERROR_FILE_NOT_OPEN					-50
#define ERROR_FILE_OLD_STATE				-51

#define ERROR_PARSE_TERMS					-102
#define ERROR_PARSE_FLOAT					-103
#define ERROR_PARSE_NAME_STRING				-104
#define ERROR_PARSE_NAME					-105
#define ERROR_PARSE_REGION_TYPE				-106
#define ERROR_PARSE_CAVITY_TYPE				-107
#define ERROR_PARSE_MIRROR_TYPE				-108
#define ERROR_PARSE_DOUBLE_REPEAT			-109
#define ERROR_PARSE_NO_REPEAT_START			-110
#define ERROR_PARSE_UNKNOWN_SYMBOL			-111
#define ERROR_PARSE_FUNCTION				-112
#define ERROR_PARSE_MODEL_INVALID		 	-113
#define ERROR_PARSE_MODEL_INCORRECT_TERMS	-114
#define ERROR_PARSE_MODEL_UNKNOWN		 	-115
#define ERROR_PARSE_LONG					-116
#define ERROR_PARSE_RADIUS					-117
#define ERROR_PARSE_KEYWORD					-118

#define ERROR_DEVICE_NO_GRID				-150
#define ERROR_DEVICE_NO_STRUCTURE			-151
#define ERROR_DEVICE_DOPING_LENGTH			-152
#define ERROR_DEVICE_GRID_LENGTH			-153
#define ERROR_DEVICE_NUMBER_CAVITY			-154
#define ERROR_DEVICE_NUMBER_MIRROR			-155
#define ERROR_DEVICE_MIRROR_REF				-156
#define ERROR_DEVICE_REGION_LENGTH			-157
#define ERROR_DEVICE_MATERIAL_PARAM_LENGTH	-159

#define ERROR_MAT_INVALID_NAME				-200
#define ERROR_MAT_INVALID_TYPE				-201

#define ERROR_ALLOY_INVALID_NAME			-250
#define ERROR_ALLOY_INVALID_TYPE			-251

#define ERROR_SIMULATION					-300

#define ERROR_FUNCTION_TRANSLATE			-350


// WARNING parameters
#define WARNING_PLOT_SAME_SCALE		1

enum FlagType { FREE_ELECTRON=1, BOUND_ELECTRON, FREE_HOLE, BOUND_HOLE,
				ELECTRON, HOLE, GRID_ELECTRICAL, GRID_OPTICAL, NODE,
				QW_ELECTRON, QW_HOLE, QUANTUM_WELL, MODE, MIRROR, CAVITY,
				CONTACT, SURFACE, DEVICE, ENVIRONMENT, SPECTRUM };

enum FlagGroup { EFFECT_FLAGS=1, VALUE_FLAGS };

enum FlagCombo { COMBO_BAND, COMBO_RECOMB, COMBO_ELECTROSTATICS,
				 COMBO_CURRENT, COMBO_FREE_CONC, COMBO_BOUND_CONC,
				 COMBO_TOTAL_CONC, COMBO_ALL_CONC, COMBO_DOPING,
				 COMBO_MATERIAL, COMBO_LASER, COMBO_INCIDENT_SPECTRUM,
				 COMBO_STRUCTURE, COMBO_RETURN_ALL, };

#define START_FLAG_TYPE		FREE_ELECTRON
#define END_FLAG_TYPE		SPECTRUM
#define NUMBER_FLAG_TYPES	20

#define VALUE_CLEAR_ALL	0x00000000L
#define VALUE_NONE		0x00000000L

//**************************************** Effects Flags ***************************************
// GRID effect flags.
#define GRID_RECOMB_SHR				0x00000001L
#define GRID_RECOMB_B_B				0x00000002L
#define GRID_RECOMB_STIM			0x00000004L
#define GRID_FERMI_DIRAC			0x00000008L
#define GRID_QW_FREE_CARR			0x00000010L
#define GRID_BAND_NARROWING			0x00000020L
#define GRID_TEMP_THERMAL_COND		0x00000040L
#define GRID_LATERAL_HEAT			0x00000080L
#define GRID_JOULE_HEAT				0x00000100L
#define GRID_THERMOELECTRIC_HEAT	0x00000200L
#define GRID_THERMIONIC				0x00000400L
#define GRID_TUNNELING				0x00000800L
#define GRID_OPTICAL_GEN			0x00001000L
#define GRID_INCIDENT_REFLECTION	0x00002000L
#define GRID_RELAX					0x00004000L
#define GRID_TEMP_MODE_PERM			0x00008000L
#define GRID_TEMP_INC_PERM			0x00010000L
#define GRID_INCOMPLETE_IONIZATION	0x00020000L
#define GRID_TEMP_MOBILITY			0x00040000L
#define GRID_DOPING_MOBILITY		0x00080000L
#define GRID_TEMP_ELECTRON_AFFINITY	0x00100000L
#define GRID_ABRUPT_MATERIALS		0x00200000L
#define GRID_RECOMB_AUGER			0x00400000L

#define GRID_EFFECTS_ALL            GRID_RECOMB_SHR	| GRID_RECOMB_B_B | GRID_RECOMB_STIM | GRID_FERMI_DIRAC	| \
									GRID_QW_FREE_CARR | GRID_BAND_NARROWING	| GRID_TEMP_THERMAL_COND | \
									GRID_LATERAL_HEAT | GRID_JOULE_HEAT	| GRID_THERMOELECTRIC_HEAT | GRID_THERMIONIC | \
									GRID_TUNNELING | GRID_OPTICAL_GEN | GRID_INCIDENT_REFLECTION | GRID_RELAX | \
									GRID_TEMP_MODE_PERM | GRID_TEMP_INC_PERM | GRID_INCOMPLETE_IONIZATION | \
									GRID_TEMP_MOBILITY | GRID_DOPING_MOBILITY | GRID_TEMP_ELECTRON_AFFINITY | \
                                    GRID_ABRUPT_MATERIALS | GRID_RECOMB_AUGER

#define GRID_EFFECTS_MAX			GRID_RECOMB_AUGER

// QW effect flags.
#define QW_INFINITE_SQRWELL			0x00000001L
#define QW_FINITE_SQRWELL			0x00000002L
#define QW_EXACT					0x00000004L

#define QW_EFFECTS_ALL              QW_INFINITE_SQRWELL	| QW_FINITE_SQRWELL	| QW_EXACT
#define QW_EFFECTS_MAX				QW_EXACT

// MODE effect flags.
#define MODE_COMPUTE				0x00000001L
#define MODE_SEARCH_WAVELENGTH		0x00000002L

#define MODE_EFFECTS_ALL			MODE_COMPUTE | MODE_SEARCH_WAVELENGTH
#define MODE_EFFECTS_MAX	   		MODE_SEARCH_WAVELENGTH

// CONTACT effect flags.
#define CONTACT_IDEALOHMIC			0x00000001L
#define CONTACT_FINITERECOMB        0x00000002L
#define CONTACT_SCHOTTKY			0x00000004L

#define CONTACT_EFFECTS_ALL         CONTACT_IDEALOHMIC | CONTACT_FINITERECOMB | CONTACT_SCHOTTKY
#define CONTACT_EFFECTS_MAX			CONTACT_SCHOTTKY

// SURFACE effect flags.
#define SURFACE_HEAT_SINK			0x00000001L

#define SURFACE_EFFECTS_ALL			SURFACE_HEAT_SINK
#define SURFACE_EFFECTS_MAX			SURFACE_HEAT_SINK

// DEVICE effect flags.
#define DEVICE_LASER				0x00000001L
#define DEVICE_VARY_LATTICE_TEMP	0x00000002L
#define DEVICE_VARY_ELECTRON_TEMP	0x00000004L
#define DEVICE_VARY_HOLE_TEMP		0x00000008L
#define DEVICE_SINGLE_TEMP			0x00000010L
#define DEVICE_NON_ISOTHERMAL		0x00000020L

#define DEVICE_EFFECTS_ALL          DEVICE_LASER | DEVICE_VARY_LATTICE_TEMP | DEVICE_VARY_ELECTRON_TEMP | \
									DEVICE_VARY_HOLE_TEMP | DEVICE_SINGLE_TEMP | DEVICE_NON_ISOTHERMAL
#define DEVICE_EFFECTS_MAX			DEVICE_NON_ISOTHERMAL

// ENVIRONMENT effect flags.
#define ENV_OPTICAL_GEN				0x00000001L
#define ENV_INCIDENT_REFLECTION		0x00000002L
#define ENV_CLAMP_POTENTIAL			0x00000004L
#define ENV_SPEC_ENTIRE_DEVICE		0x00000008L
#define ENV_SPEC_LEFT_INCIDENT		0x00000010L
#define ENV_UNDO_SIMULATION			0x00000020L
#define ENV_CLAMP_TEMPERATURE		0x00000040L

#define ENV_EFFECTS_ALL             ENV_OPTICAL_GEN	| ENV_INCIDENT_REFLECTION | ENV_CLAMP_POTENTIAL | \
									ENV_SPEC_ENTIRE_DEVICE | ENV_SPEC_LEFT_INCIDENT | ENV_UNDO_SIMULATION | \
									ENV_CLAMP_TEMPERATURE
#define ENV_EFFECTS_MAX             ENV_CLAMP_TEMPERATURE

//************************************* Value Flags ********************************************

// FREE_ELECTRON Values
#define NON_EQUIL_DOS           0x00000001L
#define EQUIL_DOS               0x00000002L
#define MOBILITY                0x00000004L
#define CONCENTRATION           0x00000008L

#define FREE_ELECTRON_ALL       NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION
#define FREE_ELECTRON_PLOT      NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION
#define FREE_ELECTRON_WRITE		NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION
#define FREE_ELECTRON_MACRO		NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION
#define FREE_ELECTRON_MAX		CONCENTRATION

// BOUND_ELECTRON Values
#define NON_EQUIL_DOS			0x00000001L
#define EQUIL_DOS				0x00000002L
#define WAVE_FUNCTION			0x00000004L
#define CONCENTRATION			0x00000008L
#define ENERGY_TOP				0x00000010L

#define BOUND_ELECTRON_ALL		NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION | \
								ENERGY_TOP

#define BOUND_ELECTRON_PLOT		NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION

#define BOUND_ELECTRON_WRITE    NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION | \
								ENERGY_TOP

#define BOUND_ELECTRON_MACRO	NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION | \
								ENERGY_TOP

#define BOUND_ELECTRON_MAX		ENERGY_TOP

// FREE_HOLE Values
#define NON_EQUIL_DOS           0x00000001L
#define EQUIL_DOS               0x00000002L
#define MOBILITY                0x00000004L
#define CONCENTRATION           0x00000008L

#define FREE_HOLE_ALL			NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION
#define FREE_HOLE_PLOT			NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION
#define FREE_HOLE_WRITE			NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION
#define FREE_HOLE_MACRO			NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION
#define FREE_HOLE_MAX			CONCENTRATION

// BOUND_HOLE Values
#define NON_EQUIL_DOS			0x00000001L
#define EQUIL_DOS				0x00000002L
#define WAVE_FUNCTION			0x00000004L
#define CONCENTRATION			0x00000008L
#define ENERGY_TOP				0x00000010L

#define BOUND_HOLE_ALL			NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION | \
								ENERGY_TOP

#define BOUND_HOLE_PLOT			NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION

#define BOUND_HOLE_WRITE		NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION | \
								ENERGY_TOP

#define BOUND_HOLE_MACRO		NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION | \
								ENERGY_TOP

#define BOUND_HOLE_MAX			ENERGY_TOP

// ELECTRON Values
#define NON_EQUIL_DOS           0x00000001L
#define EQUIL_DOS               0x00000002L
#define MOBILITY                0x00000004L
#define CONCENTRATION           0x00000008L
#define BAND_EDGE               0x00000010L
#define TEMPERATURE             0x00000020L
#define STIMULATED_FACTOR       0x00000040L
#define DOS_MASS                0x00000080L
#define COND_MASS				0x00000100L
#define PLANCK_POT              0x00000200L
#define QUASI_FERMI             0x00000400L
#define SHR_LIFETIME            0x00000800L
#define ENERGY_LIFETIME		    0x00001000L
#define EQUIL_PLANCK_POT		0x00002000L
#define CURRENT                 0x00004000L
#define EQUIL_QUASI_FERMI		0x00008000L
#define COLLISION_FACTOR		0x00010000L
#define DOPING_CONC				0x00020000L
#define DOPING_DEGENERACY		0x00040000L
#define DOPING_LEVEL			0x00080000L
#define IONIZED_DOPING			0x00100000L
#define AUGER_COEFFICIENT		0x00200000L
#define OPTICAL_GENERATION_REF	0x00800000L
#define OPTICAL_GENERATION_KIN	0x01000000L
#define B_B_HEAT				0x02000000L
#define STIM_HEAT				0x08000000L
#define RELAX_HEAT				0x10000000L
#define SHR_HEAT				0x20000000L
#define TOTAL_HEAT				0x40000000L
#define AUGER_HEAT				0x80000000L

#define ELECTRON_ALL			NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION | \
								BAND_EDGE | TEMPERATURE | STIMULATED_FACTOR | DOS_MASS | \
								COND_MASS | PLANCK_POT | QUASI_FERMI | SHR_LIFETIME | \
								ENERGY_LIFETIME | EQUIL_PLANCK_POT | CURRENT | EQUIL_QUASI_FERMI | \
								COLLISION_FACTOR | DOPING_CONC | DOPING_DEGENERACY | DOPING_LEVEL | \
								IONIZED_DOPING | AUGER_COEFFICIENT | OPTICAL_GENERATION_REF | \
								OPTICAL_GENERATION_KIN | B_B_HEAT | STIM_HEAT | \
								RELAX_HEAT | SHR_HEAT | TOTAL_HEAT | AUGER_HEAT

#define ELECTRON_PLOT			CONCENTRATION | \
								BAND_EDGE | TEMPERATURE | STIMULATED_FACTOR | DOS_MASS | \
								COND_MASS | QUASI_FERMI | SHR_LIFETIME | \
								ENERGY_LIFETIME | CURRENT | \
								COLLISION_FACTOR | DOPING_CONC | DOPING_DEGENERACY | DOPING_LEVEL | \
								IONIZED_DOPING | AUGER_COEFFICIENT | OPTICAL_GENERATION_REF | \
								OPTICAL_GENERATION_KIN | B_B_HEAT | STIM_HEAT | \
								RELAX_HEAT | SHR_HEAT | TOTAL_HEAT | AUGER_HEAT

#define ELECTRON_WRITE			CONCENTRATION | \
								BAND_EDGE | TEMPERATURE | STIMULATED_FACTOR | DOS_MASS | \
								COND_MASS | QUASI_FERMI | SHR_LIFETIME | \
								ENERGY_LIFETIME | CURRENT | \
								COLLISION_FACTOR | DOPING_CONC | DOPING_DEGENERACY | DOPING_LEVEL |\
								IONIZED_DOPING | AUGER_COEFFICIENT | OPTICAL_GENERATION_REF | \
								OPTICAL_GENERATION_KIN | B_B_HEAT | STIM_HEAT | \
								RELAX_HEAT | SHR_HEAT | TOTAL_HEAT | AUGER_HEAT

#define ELECTRON_MACRO			CONCENTRATION | \
								BAND_EDGE | TEMPERATURE | STIMULATED_FACTOR | DOS_MASS | \
								COND_MASS | QUASI_FERMI | SHR_LIFETIME | \
								ENERGY_LIFETIME | CURRENT | \
								COLLISION_FACTOR | DOPING_CONC | DOPING_DEGENERACY | DOPING_LEVEL | \
								IONIZED_DOPING | AUGER_COEFFICIENT | OPTICAL_GENERATION_REF | \
								OPTICAL_GENERATION_KIN | B_B_HEAT | STIM_HEAT | \
								RELAX_HEAT | SHR_HEAT | TOTAL_HEAT | AUGER_HEAT

#define ELECTRON_MAX			AUGER_HEAT

// HOLE Values
#define NON_EQUIL_DOS           0x00000001L
#define EQUIL_DOS               0x00000002L
#define MOBILITY                0x00000004L
#define CONCENTRATION           0x00000008L
#define BAND_EDGE               0x00000010L
#define TEMPERATURE             0x00000020L
#define STIMULATED_FACTOR       0x00000040L
#define DOS_MASS                0x00000080L
#define COND_MASS				0x00000100L
#define PLANCK_POT              0x00000200L
#define QUASI_FERMI             0x00000400L
#define SHR_LIFETIME            0x00000800L
#define ENERGY_LIFETIME		    0x00001000L
#define EQUIL_PLANCK_POT		0x00002000L
#define CURRENT                 0x00004000L
#define EQUIL_QUASI_FERMI		0x00008000L
#define COLLSION_FACTOR			0x00010000L
#define DOPING_CONC				0x00020000L
#define DOPING_DEGENERACY		0x00040000L
#define DOPING_LEVEL			0x00080000L
#define IONIZED_DOPING			0x00100000L
#define AUGER_COEFFICIENT		0x00200000L
#define OPTICAL_GENERATION_REF	0x00800000L
#define OPTICAL_GENERATION_KIN	0x01000000L
#define B_B_HEAT				0x02000000L
#define STIM_HEAT				0x08000000L
#define RELAX_HEAT				0x10000000L
#define SHR_HEAT				0x20000000L
#define TOTAL_HEAT				0x40000000L
#define AUGER_HEAT				0x80000000L

#define HOLE_ALL				NON_EQUIL_DOS | EQUIL_DOS | MOBILITY | CONCENTRATION | \
								BAND_EDGE | TEMPERATURE | STIMULATED_FACTOR | DOS_MASS | \
								COND_MASS | PLANCK_POT | QUASI_FERMI | SHR_LIFETIME | \
								ENERGY_LIFETIME | EQUIL_PLANCK_POT | CURRENT | EQUIL_QUASI_FERMI | \
								COLLISION_FACTOR | DOPING_CONC | DOPING_DEGENERACY | DOPING_LEVEL | \
								IONIZED_DOPING | AUGER_COEFFICIENT | OPTICAL_GENERATION_REF | \
								OPTICAL_GENERATION_KIN | B_B_HEAT | STIM_HEAT | \
								RELAX_HEAT | SHR_HEAT | TOTAL_HEAT | AUGER_HEAT

#define HOLE_PLOT				CONCENTRATION | \
								BAND_EDGE | TEMPERATURE | STIMULATED_FACTOR | DOS_MASS | \
								COND_MASS | QUASI_FERMI | SHR_LIFETIME | \
								ENERGY_LIFETIME | CURRENT | \
								COLLISION_FACTOR | DOPING_CONC | DOPING_DEGENERACY | DOPING_LEVEL | \
								IONIZED_DOPING | AUGER_COEFFICIENT | OPTICAL_GENERATION_REF | \
								OPTICAL_GENERATION_KIN | B_B_HEAT | STIM_HEAT | \
								RELAX_HEAT | SHR_HEAT | TOTAL_HEAT | AUGER_HEAT

#define HOLE_WRITE				CONCENTRATION | \
								BAND_EDGE | TEMPERATURE | STIMULATED_FACTOR | DOS_MASS | \
								COND_MASS | QUASI_FERMI | SHR_LIFETIME | \
								ENERGY_LIFETIME | CURRENT | \
								COLLISION_FACTOR | DOPING_CONC | DOPING_DEGENERACY | DOPING_LEVEL |\
								IONIZED_DOPING | AUGER_COEFFICIENT | OPTICAL_GENERATION_REF | \
								OPTICAL_GENERATION_KIN | B_B_HEAT | STIM_HEAT | \
								RELAX_HEAT | SHR_HEAT | TOTAL_HEAT | AUGER_HEAT

#define HOLE_MACRO				CONCENTRATION | \
								BAND_EDGE | TEMPERATURE | STIMULATED_FACTOR | DOS_MASS | \
								COND_MASS | QUASI_FERMI | SHR_LIFETIME | \
								ENERGY_LIFETIME | CURRENT | \
								COLLISION_FACTOR | DOPING_CONC | DOPING_DEGENERACY | DOPING_LEVEL | \
								IONIZED_DOPING | AUGER_COEFFICIENT | OPTICAL_GENERATION_REF | \
								OPTICAL_GENERATION_KIN | B_B_HEAT | STIM_HEAT | \
								RELAX_HEAT | SHR_HEAT | TOTAL_HEAT | AUGER_HEAT

#define HOLE_MAX				AUGER_HEAT

// GRID_ELECTRICAL Values
#define POSITION                0x00000001L
#define EFFECTS                 0x00000002L
#define NODE_NUMBER				0x00000004L
#define NODE_TYPE               0x00000008L
#define REGION_TYPE             0x00000010L
#define TEMPERATURE             0x00000020L
#define BAND_GAP                0x00000040L
#define MATERIAL                0x00000080L
#define ALLOY_TYPE              0x00000100L
#define ALLOY_CONC              0x00000200L
#define FIELD					0x00000400L
#define RADIUS                  0x00000800L
#define B_B_RECOMB_CONSTANT		0x00001000L
#define THERMAL_CONDUCT         0x00008000L
#define LATERAL_THERMAL_CONDUCT 0x00010000L
#define POTENTIAL               0x00200000L
#define VACUUM_LEVEL            0x00400000L
#define ELECTRON_AFFINITY       0x00800000L
#define	PERMITIVITY             0x01000000L

#define GRID_ELECTRICAL_ALL		POSITION | EFFECTS | NODE_NUMBER | NODE_TYPE | \
								REGION_TYPE | TEMPERATURE | BAND_GAP | MATERIAL | \
								ALLOY_TYPE | ALLOY_CONC | FIELD | RADIUS | \
								B_B_RECOMB_CONSTANT | THERMAL_CONDUCT | \
								LATERAL_THERMAL_CONDUCT | \
								POTENTIAL | VACUUM_LEVEL | ELECTRON_AFFINITY | \
								PERMITIVITY

#define GRID_ELECTRICAL_PLOT 	POSITION | \
								TEMPERATURE | BAND_GAP | \
								ALLOY_CONC | FIELD | RADIUS | \
								B_B_RECOMB_CONSTANT | THERMAL_CONDUCT | \
								LATERAL_THERMAL_CONDUCT | \
								POTENTIAL | VACUUM_LEVEL | ELECTRON_AFFINITY | \
								PERMITIVITY

#define GRID_ELECTRICAL_WRITE   POSITION | \
								REGION_TYPE | TEMPERATURE | BAND_GAP | MATERIAL | \
								ALLOY_TYPE | ALLOY_CONC | FIELD | RADIUS | \
								B_B_RECOMB_CONSTANT | THERMAL_CONDUCT | \
								LATERAL_THERMAL_CONDUCT | \
								POTENTIAL | VACUUM_LEVEL | ELECTRON_AFFINITY | \
								PERMITIVITY

#define GRID_ELECTRICAL_MACRO   \
								TEMPERATURE | BAND_GAP | \
								FIELD | \
								B_B_RECOMB_CONSTANT | THERMAL_CONDUCT | \
								LATERAL_THERMAL_CONDUCT | \
								POTENTIAL | VACUUM_LEVEL | ELECTRON_AFFINITY | \
								PERMITIVITY

#define GRID_ELECTRICAL_MAX		PERMITIVITY

// GRID_OPTICAL Values
#define INCIDENT_OVERFLOW			0x00000001L
#define INCIDENT_IMPEDANCE_REAL     0x00000002L
#define INCIDENT_IMPEDANCE_IMAG     0x00000004L
#define MODE_IMPEDANCE_REAL         0x00000008L
#define MODE_IMPEDANCE_IMAG         0x00000010L
#define INCIDENT_PHOTON_ENERGY		0x00000020L
#define INCIDENT_PHOTON_WAVELENGTH  0x00000040L
#define INCIDENT_TOTAL_POYNTING		0x00000080L
#define MODE_PHOTON_ENERGY			0x00000100L
#define MODE_PHOTON_WAVELENGTH		0x00000200L
#define	MODE_TOTAL_POYNTING			0x00000400L
#define MODE_TOTAL_PHOTONS			0x00000800L
#define MODE_GROUP_VELOCITY			0x00001000L
#define MODE_PHOTON_DENSITY			0x00002000L
#define INCIDENT_REFRACTIVE_INDEX  	0x00004000L
#define INCIDENT_ABSORPTION			0x00008000L
#define INCIDENT_TOTAL_FIELD_MAG   	0x00010000L
#define MODE_REFRACTIVE_INDEX      	0x00020000L
#define MODE_ABSORPTION         	0x00040000L
#define MODE_GAIN               	0x00080000L
#define MODE_TOTAL_FIELD_MAG       	0x00100000L
#define INCIDENT_FORWARD_FIELD_REAL 0x00200000L
#define INCIDENT_FORWARD_FIELD_IMAG 0x00400000L
#define INCIDENT_FORWARD_POYNTING	0x00800000L
#define INCIDENT_REVERSE_FIELD_REAL 0x01000000L
#define INCIDENT_REVERSE_FIELD_IMAG 0x02000000L
#define INCIDENT_REVERSE_POYNTING   0x04000000L
#define MODE_FORWARD_FIELD_REAL     0x08000000L
#define MODE_FORWARD_FIELD_IMAG		0x10000000L
#define MODE_REVERSE_FIELD_REAL		0x20000000L
#define MODE_REVERSE_FIELD_IMAG		0x40000000L


#define GRID_OPTICAL_ALL			INCIDENT_OVERFLOW | INCIDENT_IMPEDANCE_REAL | INCIDENT_IMPEDANCE_IMAG | MODE_IMPEDANCE_REAL | \
									MODE_IMPEDANCE_IMAG | INCIDENT_PHOTON_ENERGY | INCIDENT_PHOTON_WAVELENGTH | INCIDENT_TOTAL_POYNTING | \
									MODE_PHOTON_ENERGY | MODE_PHOTON_WAVELENGTH	| MODE_TOTAL_POYNTING | MODE_TOTAL_PHOTONS | \
									MODE_GROUP_VELOCITY	| MODE_PHOTON_DENSITY | INCIDENT_REFRACTIVE_INDEX | INCIDENT_ABSORPTION | \
									INCIDENT_TOTAL_FIELD_MAG | MODE_REFRACTIVE_INDEX | MODE_ABSORPTION | MODE_GAIN | \
									MODE_TOTAL_FIELD_MAG | INCIDENT_FORWARD_FIELD_REAL | INCIDENT_FORWARD_FIELD_IMAG | \
									INCIDENT_FORWARD_POYNTING | \
									INCIDENT_REVERSE_FIELD_REAL | INCIDENT_REVERSE_FIELD_IMAG | \
									INCIDENT_REVERSE_POYNTING | MODE_FORWARD_FIELD_REAL | \
									MODE_FORWARD_FIELD_IMAG	| MODE_REVERSE_FIELD_REAL | MODE_REVERSE_FIELD_IMAG


#define GRID_OPTICAL_PLOT		    INCIDENT_TOTAL_POYNTING | \
									MODE_PHOTON_DENSITY | INCIDENT_REFRACTIVE_INDEX | INCIDENT_ABSORPTION | \
									INCIDENT_TOTAL_FIELD_MAG | MODE_REFRACTIVE_INDEX | MODE_ABSORPTION | MODE_GAIN | \
									MODE_TOTAL_FIELD_MAG | INCIDENT_FORWARD_FIELD_REAL | INCIDENT_FORWARD_FIELD_IMAG | \
									INCIDENT_FORWARD_POYNTING | \
									INCIDENT_REVERSE_FIELD_REAL | INCIDENT_REVERSE_FIELD_IMAG | \
									INCIDENT_REVERSE_POYNTING | MODE_FORWARD_FIELD_REAL | \
									MODE_FORWARD_FIELD_IMAG	| MODE_REVERSE_FIELD_REAL | MODE_REVERSE_FIELD_IMAG

#define GRID_OPTICAL_WRITE			INCIDENT_TOTAL_POYNTING | \
									MODE_PHOTON_DENSITY | INCIDENT_REFRACTIVE_INDEX | INCIDENT_ABSORPTION | \
									INCIDENT_TOTAL_FIELD_MAG | MODE_REFRACTIVE_INDEX | MODE_ABSORPTION | MODE_GAIN | \
									MODE_TOTAL_FIELD_MAG | INCIDENT_FORWARD_FIELD_REAL | INCIDENT_FORWARD_FIELD_IMAG | \
									INCIDENT_FORWARD_POYNTING | \
									INCIDENT_REVERSE_FIELD_REAL | INCIDENT_REVERSE_FIELD_IMAG | \
									INCIDENT_REVERSE_POYNTING | MODE_FORWARD_FIELD_REAL | \
									MODE_FORWARD_FIELD_IMAG	| MODE_REVERSE_FIELD_REAL | MODE_REVERSE_FIELD_IMAG

#define GRID_OPTICAL_MACRO			INCIDENT_TOTAL_POYNTING | \
									MODE_PHOTON_DENSITY | INCIDENT_REFRACTIVE_INDEX | INCIDENT_ABSORPTION | \
									INCIDENT_TOTAL_FIELD_MAG | MODE_REFRACTIVE_INDEX | MODE_ABSORPTION | MODE_GAIN | \
									MODE_TOTAL_FIELD_MAG | INCIDENT_FORWARD_FIELD_REAL | INCIDENT_FORWARD_FIELD_IMAG | \
									INCIDENT_FORWARD_POYNTING | \
									INCIDENT_REVERSE_FIELD_REAL | INCIDENT_REVERSE_FIELD_IMAG | \
									INCIDENT_REVERSE_POYNTING | MODE_FORWARD_FIELD_REAL | \
									MODE_FORWARD_FIELD_IMAG	| MODE_REVERSE_FIELD_REAL | MODE_REVERSE_FIELD_IMAG

#define GRID_OPTICAL_MAX			MODE_REVERSE_FIELD_IMAG

// NODE Values
#define REDUCED_DOS_MASS        0x00000001L
#define TOTAL_CHARGE            0x00000002L
#define TOTAL_CURRENT           0x00000008L
#define INTRINSIC_CONC          0x00000080L
#define TOTAL_RECOMB            0x00000200L
#define SHR_RECOMB              0x00000400L
#define B_B_RECOMB              0x00000800L
#define AUGER_RECOMB			0x00002000L
#define OPTICAL_GENERATION		0x00004000L
#define STIM_RECOMB             0x00010000L
#define TOTAL_RADIATIVE_HEAT    0x00040000L
#define B_B_HEAT				0x02000000L
#define OPTICAL_GENERATION_HEAT	0x04000000L
#define STIM_HEAT				0x08000000L
#define TOTAL_HEAT				0x40000000L

#define NODE_ALL                REDUCED_DOS_MASS | TOTAL_CHARGE | TOTAL_CURRENT | \
								INTRINSIC_CONC | \
								TOTAL_RECOMB | SHR_RECOMB | B_B_RECOMB | AUGER_RECOMB | \
								OPTICAL_GENERATION | \
								STIM_RECOMB	| TOTAL_RADIATIVE_HEAT | \
								B_B_HEAT | OPTICAL_GENERATION_HEAT | STIM_HEAT | \
								TOTAL_HEAT

#define NODE_PLOT				REDUCED_DOS_MASS | TOTAL_CHARGE | TOTAL_CURRENT | \
								INTRINSIC_CONC | \
								TOTAL_RECOMB | SHR_RECOMB | B_B_RECOMB | AUGER_RECOMB | \
								OPTICAL_GENERATION | \
								STIM_RECOMB	| TOTAL_RADIATIVE_HEAT | \
								B_B_HEAT | OPTICAL_GENERATION_HEAT | STIM_HEAT | \
								TOTAL_HEAT

#define NODE_WRITE              REDUCED_DOS_MASS | TOTAL_CHARGE | TOTAL_CURRENT | \
								INTRINSIC_CONC | \
								TOTAL_RECOMB | SHR_RECOMB | B_B_RECOMB | AUGER_RECOMB | \
								OPTICAL_GENERATION | \
								STIM_RECOMB	| TOTAL_RADIATIVE_HEAT | \
								B_B_HEAT | OPTICAL_GENERATION_HEAT | STIM_HEAT | \
								TOTAL_HEAT

#define NODE_MACRO              REDUCED_DOS_MASS | TOTAL_CHARGE | TOTAL_CURRENT | \
								INTRINSIC_CONC | \
								TOTAL_RECOMB | SHR_RECOMB | B_B_RECOMB | AUGER_RECOMB | \
								OPTICAL_GENERATION | \
								STIM_RECOMB	| TOTAL_RADIATIVE_HEAT | \
								B_B_HEAT | OPTICAL_GENERATION_HEAT | STIM_HEAT | \
								TOTAL_HEAT

#define NODE_MAX				TOTAL_HEAT

// QW_ELECTRON Values
#define NON_EQUIL_DOS			0x00000001L
#define EQUIL_DOS				0x00000002L
#define WAVE_FUNCTION			0x00000004L
#define CONCENTRATION			0x00000008L
#define ENERGY_TOP				0x00000010L
#define ENERGY_LEVEL            0x00000020L
#define STIMULATED_FACTOR       0x00000040L
#define EQUIL_PLANCK_POT		0x00002000L
#define DOPING_CONC				0x00020000L
#define AUGER_COEFFICIENT		0x00200000L

#define QW_ELECTRON_ALL			NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION | \
								ENERGY_TOP | ENERGY_LEVEL | STIMULATED_FACTOR | \
								EQUIL_PLANCK_POT | DOPING_CONC | AUGER_COEFFICIENT

#define QW_ELECTRON_PLOT		VALUE_NONE

#define QW_ELECTRON_WRITE       NON_EQUIL_DOS | EQUIL_DOS | CONCENTRATION | \
								ENERGY_TOP | ENERGY_LEVEL | STIMULATED_FACTOR | \
                                AUGER_COEFFICIENT

#define QW_ELECTRON_MACRO		NON_EQUIL_DOS | EQUIL_DOS | CONCENTRATION | \
								ENERGY_TOP | ENERGY_LEVEL | STIMULATED_FACTOR | \
                                AUGER_COEFFICIENT

#define QW_ELECTRON_MAX			AUGER_COEFFICIENT

// QW_HOLE Values
#define NON_EQUIL_DOS			0x00000001L
#define EQUIL_DOS				0x00000002L
#define WAVE_FUNCTION			0x00000004L
#define CONCENTRATION			0x00000008L
#define ENERGY_TOP				0x00000010L
#define ENERGY_LEVEL            0x00000020L
#define STIMULATED_FACTOR       0x00000040L
#define EQUIL_PLANCK_POT		0x00002000L
#define DOPING_CONC				0x00020000L
#define AUGER_COEFFICIENT		0x00200000L

#define QW_HOLE_ALL				NON_EQUIL_DOS | EQUIL_DOS | WAVE_FUNCTION | CONCENTRATION | \
								ENERGY_TOP | ENERGY_LEVEL | STIMULATED_FACTOR | \
								EQUIL_PLANCK_POT | DOPING_CONC | AUGER_COEFFICIENT

#define QW_HOLE_PLOT			VALUE_NONE

#define QW_HOLE_WRITE       	NON_EQUIL_DOS | EQUIL_DOS | CONCENTRATION | \
								ENERGY_TOP | ENERGY_LEVEL | STIMULATED_FACTOR | \
                                AUGER_COEFFICIENT

#define QW_HOLE_MACRO			NON_EQUIL_DOS | EQUIL_DOS | CONCENTRATION | \
								ENERGY_TOP | ENERGY_LEVEL | STIMULATED_FACTOR | \
                                AUGER_COEFFICIENT

#define QW_HOLE_MAX				AUGER_COEFFICIENT

// QUANTUM_WELL Values
#define POSITION                0x00000001L
#define EFFECTS					0x00000002L
#define MIDPOINT                0x00000004L
#define NUMBER_NODES            0x00000008L
#define LENGTH                  0x00000010L
#define TEMPERATURE             0x00000020L
#define BAND_GAP                0x00000040L
#define INTRINSIC_CONC          0x00000080L
#define OVERLAP                 0x00000100L
#define TOTAL_RECOMB            0x00000200L
#define SHR_RECOMB              0x00000400L
#define B_B_RECOMB              0x00000800L
#define B_B_RECOMB_CONSTANT     0x00001000L
#define AUGER_RECOMB			0x00002000L
#define INCIDENT_ABSORPTION		0x00008000L
#define MODE_ABSORPTION         0x00040000L
#define MODE_GAIN               0x00080000L
#define B_B_HEAT                0x02000000L

#define QUANTUM_WELL_ALL		POSITION | EFFECTS | MIDPOINT | NUMBER_NODES | \
								LENGTH | TEMPERATURE | BAND_GAP | INTRINSIC_CONC | \
								OVERLAP | TOTAL_RECOMB | SHR_RECOMB | B_B_RECOMB | AUGER_RECOMB | \
								B_B_RECOMB_CONSTANT | INCIDENT_ABSORPTION | \
								MODE_ABSORPTION | MODE_GAIN | B_B_HEAT

#define QUANTUM_WELL_PLOT	   	VALUE_NONE

#define QUANTUM_WELL_WRITE		POSITION | NUMBER_NODES | \
								LENGTH | BAND_GAP | INTRINSIC_CONC | \
								OVERLAP | SHR_RECOMB | B_B_RECOMB | AUGER_RECOMB | \
								B_B_RECOMB_CONSTANT | INCIDENT_ABSORPTION | \
								MODE_ABSORPTION | MODE_GAIN


#define QUANTUM_WELL_MACRO      \
								BAND_GAP | INTRINSIC_CONC | \
								OVERLAP | SHR_RECOMB | B_B_RECOMB | AUGER_RECOMB | \
								\
								MODE_GAIN

#define QUANTUM_WELL_MAX		B_B_HEAT

// MODE Values
#define PHOTON_LIFETIME         0x00000001L
#define EFFECTS					0x00000002L
#define MIRROR_LOSS             0x00000004L
#define WAVEGUIDE_LOSS          0x00000008L
#define TOTAL_SPONTANEOUS       0x00000010L
#define MODE_NORMALIZATION		0x00000020L
#define SPONT_FACTOR            0x00000040L
#define MODE_PHOTON_ENERGY		0x00000100L
#define MODE_PHOTON_WAVELENGTH	0x00000200L
#define MODE_TOTAL_PHOTONS		0x00000800L
#define MODE_GROUP_VELOCITY		0x00001000L
#define MODE_GAIN               0x00080000L
#define MODE_TOTAL_FIELD_MAG    0x00100000L

#define MODE_ALL				PHOTON_LIFETIME	| EFFECTS | MIRROR_LOSS | WAVEGUIDE_LOSS | \
								TOTAL_SPONTANEOUS | MODE_NORMALIZATION | SPONT_FACTOR | \
								MODE_PHOTON_ENERGY |MODE_PHOTON_WAVELENGTH | MODE_TOTAL_PHOTONS | \
								MODE_GROUP_VELOCITY | \
								MODE_GAIN | \
								MODE_TOTAL_FIELD_MAG

#define MODE_PLOT				VALUE_NONE

#define MODE_WRITE				PHOTON_LIFETIME	| MIRROR_LOSS | WAVEGUIDE_LOSS | \
								TOTAL_SPONTANEOUS | SPONT_FACTOR | \
								MODE_PHOTON_ENERGY |MODE_PHOTON_WAVELENGTH | MODE_TOTAL_PHOTONS | \
								MODE_GROUP_VELOCITY | \
								MODE_GAIN

#define MODE_MACRO				PHOTON_LIFETIME	| MIRROR_LOSS | WAVEGUIDE_LOSS | \
								TOTAL_SPONTANEOUS | SPONT_FACTOR | \
								MODE_PHOTON_ENERGY |MODE_PHOTON_WAVELENGTH | MODE_TOTAL_PHOTONS | \
								MODE_GROUP_VELOCITY | \
								MODE_GAIN

#define MODE_MAX				MODE_TOTAL_FIELD_MAG

// MIRROR Values
#define POSITION                0x00000001L
#define TYPE                    0x00000002L
#define NODE_NUMBER             0x00000004L
#define REFLECTIVITY            0x00000008L
#define POWER                   0x00000010L

#define MIRROR_ALL				POSITION | TYPE | NODE_NUMBER | REFLECTIVITY | \
								POWER

#define MIRROR_PLOT             VALUE_NONE

#define MIRROR_WRITE			POSITION | TYPE | REFLECTIVITY | \
								POWER

#define MIRROR_MACRO			POWER

#define MIRROR_MAX				POWER

// CAVITY Values
#define AREA                   	0x00000001L
#define TYPE                    0x00000002L
#define LENGTH                  0x00000010L

#define CAVITY_ALL				AREA | TYPE | LENGTH
#define CAVITY_PLOT				VALUE_NONE
#define CAVITY_WRITE            AREA | TYPE | LENGTH
#define CAVITY_MACRO			VALUE_NONE
#define CAVITY_MAX				LENGTH

// CONTACT Values
#define POSITION                0x00000001L
#define EFFECTS                 0x00000002L
#define NODE_NUMBER             0x00000004L
#define TOTAL_CURRENT           0x00000008L
#define ELECTRON_CURRENT        0x00000010L
#define ELECTRON_RECOMB_VEL     0x00000020L
#define EQUIL_ELECTRON_CONC		0x00000040L
#define APPLIED_BIAS            0x00000100L
#define BUILT_IN_POT            0x00000200L
#define FIELD					0x00000400L
#define HOLE_CURRENT            0x00001000L
#define HOLE_RECOMB_VEL         0x00002000L
#define EQUIL_HOLE_CONC			0x00004000L
#define BARRIER_HEIGHT			0x00008000L

#define CONTACT_ALL             POSITION | EFFECTS | NODE_NUMBER | TOTAL_CURRENT | \
								ELECTRON_CURRENT | ELECTRON_RECOMB_VEL | EQUIL_ELECTRON_CONC | \
								APPLIED_BIAS | BUILT_IN_POT | FIELD | \
								HOLE_CURRENT | HOLE_RECOMB_VEL | EQUIL_HOLE_CONC | BARRIER_HEIGHT

#define CONTACT_PLOT			VALUE_NONE

#define CONTACT_WRITE           POSITION | TOTAL_CURRENT | \
								ELECTRON_CURRENT | ELECTRON_RECOMB_VEL | EQUIL_ELECTRON_CONC | \
								APPLIED_BIAS | BUILT_IN_POT | FIELD | \
								HOLE_CURRENT | HOLE_RECOMB_VEL | EQUIL_HOLE_CONC | BARRIER_HEIGHT

#define CONTACT_MACRO			TOTAL_CURRENT | \
								ELECTRON_CURRENT | \
								APPLIED_BIAS | BUILT_IN_POT | FIELD | \
								HOLE_CURRENT

#define CONTACT_MAX			    BARRIER_HEIGHT

// SURFACE Values
#define POSITION                	0x00000001L
#define EFFECTS                 	0x00000002L
#define NODE_NUMBER                 0x00000004L
#define ELECTRON_TEMPERATURE		0x00000010L
#define TEMPERATURE                 0x00000020L
#define HOLE_TEMPERATURE			0x00000040L
#define INCIDENT_TOTAL_POYNTING		0x00000080L
#define MODE_SURFACE_FIELD			0x00000100L
#define MODE_INTERNAL_FIELD			0x00000200L
#define MODE_REVERSE_POYNTING		0x00000400L
#define INCIDENT_REFRACTIVE_INDEX   0x00004000L
#define THERMAL_CONDUCT             0x00008000L
#define INCIDENT_TOTAL_FIELD_MAG   	0x00010000L
#define MODE_REFRACTIVE_INDEX      	0x00020000L
#define INCIDENT_SURFACE_FIELD		0x00040000L
#define INCIDENT_INTERNAL_FIELD		0x00080000L
#define MODE_TOTAL_FIELD_MAG       	0x00100000L
#define INCIDENT_FORWARD_FIELD_REAL 0x00200000L
#define INCIDENT_FORWARD_FIELD_IMAG 0x00400000L
#define INCIDENT_FORWARD_POYNTING	0x00800000L
#define INCIDENT_REVERSE_FIELD_REAL 0x01000000L
#define INCIDENT_REVERSE_FIELD_IMAG 0x02000000L
#define INCIDENT_REVERSE_POYNTING   0x04000000L
#define MODE_FORWARD_FIELD_REAL     0x08000000L
#define MODE_FORWARD_FIELD_IMAG		0x10000000L
#define MODE_REVERSE_FIELD_REAL		0x20000000L
#define MODE_REVERSE_FIELD_IMAG		0x40000000L
#define MODE_FORWARD_POYNTING		0x80000000L


#define SURFACE_ALL             	POSITION | EFFECTS | NODE_NUMBER | \
									ELECTRON_TEMPERATURE | TEMPERATURE | HOLE_TEMPERATURE | INCIDENT_TOTAL_POYNTING | \
									MODE_SURFACE_FIELD | MODE_INTERNAL_FIELD | \
									INCIDENT_REFRACTIVE_INDEX | THERMAL_CONDUCT | \
									INCIDENT_TOTAL_FIELD_MAG | MODE_REFRACTIVE_INDEX |	INCIDENT_SURFACE_FIELD | \
									INCIDENT_INTERNAL_FIELD | MODE_REVERSE_POYNTING | MODE_TOTAL_FIELD_MAG | INCIDENT_FORWARD_FIELD_REAL | \
									INCIDENT_FORWARD_FIELD_IMAG | INCIDENT_FORWARD_POYNTING | INCIDENT_REVERSE_FIELD_REAL | \
									INCIDENT_REVERSE_FIELD_IMAG | INCIDENT_REVERSE_POYNTING | MODE_FORWARD_FIELD_REAL | \
									MODE_FORWARD_FIELD_IMAG | MODE_REVERSE_FIELD_REAL | MODE_REVERSE_FIELD_IMAG | MODE_FORWARD_POYNTING

#define SURFACE_PLOT				VALUE_NONE

#define SURFACE_WRITE				POSITION | \
									ELECTRON_TEMPERATURE | TEMPERATURE | HOLE_TEMPERATURE | INCIDENT_TOTAL_POYNTING | \
									INCIDENT_REFRACTIVE_INDEX | THERMAL_CONDUCT | \
									INCIDENT_TOTAL_FIELD_MAG | MODE_REFRACTIVE_INDEX |	\
									MODE_TOTAL_FIELD_MAG | INCIDENT_FORWARD_FIELD_REAL | \
									INCIDENT_FORWARD_FIELD_IMAG | INCIDENT_FORWARD_POYNTING | INCIDENT_REVERSE_FIELD_REAL | \
									INCIDENT_REVERSE_FIELD_IMAG | INCIDENT_REVERSE_POYNTING | MODE_FORWARD_FIELD_REAL | \
									MODE_FORWARD_FIELD_IMAG | MODE_REVERSE_FIELD_REAL | MODE_REVERSE_FIELD_IMAG

#define SURFACE_MACRO				\
									INCIDENT_TOTAL_POYNTING | \
									INCIDENT_TOTAL_FIELD_MAG | \
									MODE_TOTAL_FIELD_MAG | INCIDENT_FORWARD_FIELD_REAL | \
									INCIDENT_FORWARD_FIELD_IMAG | INCIDENT_FORWARD_POYNTING | INCIDENT_REVERSE_FIELD_REAL | \
									INCIDENT_REVERSE_FIELD_IMAG | INCIDENT_REVERSE_POYNTING | MODE_FORWARD_FIELD_REAL | \
									MODE_FORWARD_FIELD_IMAG | MODE_REVERSE_FIELD_REAL | MODE_REVERSE_FIELD_IMAG

#define SURFACE_MAX					MODE_FORWARD_POYNTING

// DEVICE Values
#define EFFECTS                 0x00000002L
#define CURRENT_SOLUTION        0x00000004L
#define CURRENT_STATUS          0x00000008L
#define ERROR_PSI				0x00000010L
#define ERROR_ETA_C				0x00000020L
#define ERROR_ETA_V             0x00000040L
#define ERROR_TEMP              0x00000080L
#define ERROR_MODE				0x00000100L
#define ERROR_PHOTON            0x00000200L
#define INNER_ELECT_ITER        0x00000400L
#define INNER_THERM_ITER        0x00000800L
#define INNER_MODE_ITER         0x00001000L
#define OUTER_OPTIC_ITER        0x00002000L
#define OUTER_THERM_ITER        0x00004000L

#define DEVICE_ALL			    EFFECTS | CURRENT_SOLUTION | CURRENT_STATUS | \
								ERROR_PSI | ERROR_ETA_C	| ERROR_ETA_V | ERROR_TEMP | \
								ERROR_MODE | ERROR_PHOTON | INNER_ELECT_ITER | INNER_THERM_ITER | \
								INNER_MODE_ITER | OUTER_OPTIC_ITER | OUTER_THERM_ITER

#define DEVICE_PLOT				VALUE_NONE

#define DEVICE_WRITE			CURRENT_SOLUTION | CURRENT_STATUS | \
								ERROR_PSI | ERROR_ETA_C | ERROR_ETA_V | ERROR_TEMP | \
								ERROR_MODE | ERROR_PHOTON | INNER_ELECT_ITER | INNER_THERM_ITER	| \
								INNER_MODE_ITER | OUTER_OPTIC_ITER | OUTER_THERM_ITER

#define DEVICE_MACRO            ERROR_PSI | ERROR_ETA_C | ERROR_ETA_V | ERROR_TEMP | \
								ERROR_MODE | ERROR_PHOTON

#define DEVICE_MAX				OUTER_THERM_ITER

// ENVRIONMENT Values
#define POT_CLAMP_VALUE         0x00000001L
#define EFFECTS                 0x00000002L
#define SPEC_START_POSITION     0x00000004L
#define SPEC_END_POSITION       0x00000008L
#define SPECTRUM_MULTIPLIER		0x00000010L
#define TEMPERATURE             0x00000020L
#define MAX_ELECTRICAL_ERROR    0x00000040L
#define MAX_THERMAL_ERROR		0x00000080L
#define MAX_OPTIC_ERROR			0x00000100L
#define COARSE_MODE_ERROR		0x00000200L
#define FINE_MODE_ERROR			0x00000400L
#define RADIUS                  0x00000800L
#define MAX_INNER_ELECT_ITER	0x00001000L
#define MAX_INNER_THERM_ITER	0x00002000L
#define MAX_OUTER_OPTIC_ITER	0x00004000L
#define MAX_OUTER_THERM_ITER	0x00008000L
#define MAX_INNER_MODE_ITER		0x00010000L
#define TEMP_CLAMP_VALUE		0x00020000L
#define TEMP_RELAX_VALUE		0x00040000L

#define ENVIRONMENT_ALL			POT_CLAMP_VALUE | EFFECTS | SPEC_START_POSITION | SPEC_END_POSITION | \
								SPECTRUM_MULTIPLIER | TEMPERATURE | MAX_ELECTRICAL_ERROR | MAX_THERMAL_ERROR | \
								MAX_OPTIC_ERROR | COARSE_MODE_ERROR | FINE_MODE_ERROR | RADIUS | \
								MAX_INNER_ELECT_ITER | MAX_INNER_THERM_ITER | MAX_OUTER_OPTIC_ITER	| MAX_OUTER_THERM_ITER | \
								MAX_INNER_MODE_ITER | TEMP_CLAMP_VALUE | TEMP_RELAX_VALUE

#define ENVIRONMENT_PLOT		VALUE_NONE

#define ENVIRONMENT_WRITE		POT_CLAMP_VALUE | SPEC_START_POSITION | SPEC_END_POSITION | \
								SPECTRUM_MULTIPLIER | TEMPERATURE | MAX_ELECTRICAL_ERROR | MAX_THERMAL_ERROR | \
								MAX_OPTIC_ERROR | COARSE_MODE_ERROR | FINE_MODE_ERROR | RADIUS | \
								MAX_INNER_ELECT_ITER | MAX_INNER_THERM_ITER | MAX_OUTER_OPTIC_ITER	| MAX_OUTER_THERM_ITER | \
								MAX_INNER_MODE_ITER  | TEMP_CLAMP_VALUE | TEMP_RELAX_VALUE

#define ENVIRONMENT_MACRO		VALUE_NONE

#define ENVIRONMENT_MAX			TEMP_RELAX_VALUE

// SPECTRAL Values
#define INCIDENT_PHOTON_ENERGY		0x00000020L
#define INCIDENT_PHOTON_WAVELENGTH  0x00000040L
#define INCIDENT_INPUT_INTENSITY 	0x00000080L
#define INCIDENT_EMITTED_INTENSITY	0x00000100L
#define INCIDENT_REFLECT_INTENSITY	0x00000200L

#define SPECTRUM_ALL            	INCIDENT_PHOTON_ENERGY | INCIDENT_PHOTON_WAVELENGTH | INCIDENT_INPUT_INTENSITY | \
									INCIDENT_EMITTED_INTENSITY | INCIDENT_REFLECT_INTENSITY

#define SPECTRUM_PLOT				INCIDENT_INPUT_INTENSITY | \
									INCIDENT_EMITTED_INTENSITY | INCIDENT_REFLECT_INTENSITY

#define SPECTRUM_WRITE				INCIDENT_PHOTON_ENERGY | INCIDENT_PHOTON_WAVELENGTH | INCIDENT_INPUT_INTENSITY | \
									INCIDENT_EMITTED_INTENSITY | INCIDENT_REFLECT_INTENSITY

#define SPECTRUM_MACRO				INCIDENT_INPUT_INTENSITY | \
									INCIDENT_EMITTED_INTENSITY | INCIDENT_REFLECT_INTENSITY

#define SPECTRUM_MAX				INCIDENT_REFLECT_INTENSITY

